### ISSUE TITLE
When running with 512x512, the code errors out

### ISSUE THREAD

**Issue by nairb2020** [VinAIResearch/blur-kernel-space-exploring#2]
Hi, I'm trying to run domain_specific_deblur.py with styleGAN2 on 512x512 dimension with pretrained models. However, after I fixed the latent and noise dimentions in dsd_stylegan2.py, the code still errors out on unet_parts.py. Is 512x512 supported? 

The stacktrace is as below: 

```
Traceback (most recent call last):
  File "domain_specific_deblur.py", line 84, in <module>
    for j, (HR, LR) in enumerate(model(ref_im)):
  File "/deblur/blur-kernel-space-exploring/models/dsd/dsd.py", line 188, in forward
    self.optimize_x_step(epoch)
  File "/deblur/blur-kernel-space-exploring/models/dsd/dsd.py", line 150, in optimize_x_step
    loss, loss_dict = self.loss_builder(latent_in, self.gen_im, self.gen_ker, epoch)
  File "//anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/deblur/blur-kernel-space-exploring/models/losses/dsd_loss.py", line 108, in forward
    "gen_im_lr": self.D.adaptKernel(gen_im, kernel),
  File "/work/deblur/blur-kernel-space-exploring/models/kernel_encoding/kernel_wizard.py", line 157, in adaptKernel
    out = self.adapter(x_sharp, kernel)
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "//work/deblur/blur-kernel-space-exploring/models/kernel_encoding/kernel_wizard.py", line 99, in forward
    return self.model(x, k)
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/deblur/blur-kernel-space-exploring/models/backbones/unet_parts.py", line 103, in forward
    return self.up(self.submodule(self.down(x), noise))
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/deblur/blur-kernel-space-exploring/models/backbones/unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/deblur/blur-kernel-space-exploring/models/backbones/unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/deblur/blur-kernel-space-exploring/models/backbones/unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/deblur/blur-kernel-space-exploring/models/backbones/unet_parts.py", line 107, in forward
    return torch.cat((self.up(torch.cat((self.down(x), noise), dim=1)), x), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 2 and 4 (The offending index is 0)
```

Thank you for your help!

**Comment by P0lyFish** [comment]
Thanks for your interest,
Currently, the domain-specific deblurring method only works with 256x256 images. However, if you choose StyleGAN (instead of StyleGANv2) in the config file, the output image will have size 1024x1024, so you can downsample your input image to 256x256 first and then use the domain-specific deblurring algorithm with StyleGAN, the output will be 1024x1024 (then you can downsample it to 512x512).
