### ISSUE TITLE
When I try to run generate_blur.py， I got this RuntimeError

### ISSUE THREAD

**Issue by Suncheng2019** [VinAIResearch/blur-kernel-space-exploring#9]
The size of the image which I used is 640*640. It can be diviable by 128. Thanks for your help!

Sample #0/10
Traceback (most recent call last):
  File ".\generate_blur.py", line 53, in <module>
    main()
  File ".\generate_blur.py", line 45, in main
    LQ_tensor = model.adaptKernel(HQ_tensor, kernel)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\kernel_encoding\kernel_wizard.py", line 157, in adaptKernel
    out = self.adapter(x_sharp, kernel)
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\kernel_encoding\kernel_wizard.py", line 99, in forward
    return self.model(x, k)
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\backbones\unet_parts.py", line 103, in forward
    return self.up(self.submodule(self.down(x), noise))
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\backbones\unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\backbones\unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\backbones\unet_parts.py", line 109, in forward
    return torch.cat((self.up(self.submodule(self.down(x), noise)), x), dim=1)
  File "D:\ProgramData\Anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\Pycharm\blur-kernel-space-exploring-main\models\backbones\unet_parts.py", line 107, in forward
    return torch.cat((self.up(torch.cat((self.down(x), noise), dim=1)), x), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 2 and 5 (The offending index is 0)

**Comment by Suncheng2019** [comment]
I download the pre_trained model vgg19-dcbb9e9d.pth in C:\, I can run generate_bule.py and also get the following print :
Sample #0/10
Sample #1/10
Sample #2/10
Sample #3/10
Sample #4/10
Sample #5/10
Sample #6/10
Sample #7/10
Sample #8/10
Sample #9/10
And I use this order to run it:
python generate_blur.py --yml_path=options/generate
_blur/default.yml --image_path=imgs/sharp_imgs/mushishi.png --num_samples=10 --save_path=./res.png

but I don't get the res.png , I don't know why. Could you please help me out? Thank you ver much!

**Comment by Fangzhenxuan** [comment]
你解决这个问题了吗
他的代码好像只能跑256*256大小的图片

**Comment by rose-jinyang** [comment]
Hello
Is it possible to generate a blurry image in any resolution?

**Comment by rydeveraumn** [comment]
@rose-jinyang I know your post was a long time ago did you get an answer to your question? I want to blur images of resolution 512x512.
